### ISSUE TITLE
ttv looking glass works in vods but not in clips

### ISSUE THREAD

**Issue by xSeeSx** [SpaceshipCaptain/LookingGlassTTV#1]
The search bar doesn't appear under clips, nor in chrome or firefox. But it does under vods

**Comment by SpaceshipCaptain** [comment]
Hmm I have never seen them only update the clips tags before, usually it's site wide. Thanks for the heads up and I have pushed an update to both chrome and firefox with the new tag. Firefox update is already live but you might have to check for updates in your add-ons to get it. Chrome usually takes a few hours to review the new version but it should be live within 24 hours. Thanks!

**Comment by xSeeSx** [comment]
Thank you so much!
